### ISSUE TITLE
Picture missing in documentation

### ISSUE THREAD

**Issue by BianTieyuan** [WMD-group/PDynA#10]
Hi developers,

It seems that some pictures in _Tutorials-Defining system_ and _Tutorials-2D Perovskite_ are missing. It is hard to know the bonding and connection introduced in these parts.
![8a539dba1cfcb530b5eb56677d7dc09](https://github.com/user-attachments/assets/226eb994-2b09-4b64-a8bd-125ebeb99c34)
![1728396070056](https://github.com/user-attachments/assets/d60550e9-83ae-42b5-882b-9f096fd83626)

**Comment by nukenadal** [comment]
Hi,

Thank you for posting the issue. It seems that the image is not referenced correctly. For a quick fix, you can directly download the same notebook from the examples directory, where the images are correctly shown. Further updates on the docs website will be posted here as soon as it is fixed.

**Comment by nukenadal** [comment]
The issue has now been resolved.
