### ISSUE TITLE
How to analyze trajectories containing hybrid perovskite and other elements 

### ISSUE THREAD

**Issue by PolyuWeldingSpock** [WMD-group/PDynA#4]
Hi developers of PDynA,

Recently I saw this code on arxiv and I thought this code was very useful. I tried to use this code analyze my trajectories which composed of FAPbI and water. However I found that this code seems only support several elements mainly perovskite. 
```python
    def __post_init__(self):
        
        Xsite_species = ['Cl','Br','I'] # update if needed
        Bsite_species = ['Pb','Sn'] # update if needed
        known_elem = ("I", "Br", "Cl", "Pb", "C", "H", "N", "Cs")
```
As a result, I could not analyze the tilting of FA or octahedral. I want to know that is there any solution to solve this problem, i.e. parse the perovskite part to analyze. Since many research with MD simulation do not only contain perovskite also other elements.

Thanks in advance.

Regards.

**Comment by nukenadal** [comment]
Hi,

Thank you for your interest in PDynA. 

This part of the code is precisely for users to tune according to their material systems, as the code need to know what elements will appear on each site. For example, if your structure contains only FAPI and water, you can set:
```
Xsite_species = ['I'] # update if needed
Bsite_species = ['Pb'] # update if needed
known_elem = ("I", "Pb", "C", "H", "N", "O") # update if needed
```
This part is just for checking if each appearing element in the structure is expected by the user, but will not affect the main analysis of the code. 

Please let me know if this resolves the issue. 

Best regards,
